### ISSUE TITLE
error msg when compiling

### ISSUE THREAD

**Issue by helmarw** [fowlerk/ESP8266-Color-Weather-Station-v17#3]
Arduino: 1.8.10 (Mac OS X), Board: "WeMos D1 R1, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (3M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

sketch/GfxUi.cpp: In member function 'void GfxUi::drawBmp(String, uint8_t, uint16_t)':
GfxUi.cpp:198:53: error: no matching function for call to 'Adafruit_ILI9341::writePixel(uint16_t)'
               _tft->writePixel(_tft->color565(r,g,b));
                                                     ^
sketch/GfxUi.cpp:198:53: note: candidate is:
In file included from /Users/helmar/Documents/Arduino/libraries/Adafruit_ILI9341/Adafruit_ILI9341.h:43:0,
                 from sketch/GfxUi.h:21,
                 from sketch/GfxUi.cpp:21:
/Users/helmar/Documents/Arduino/libraries/Adafruit_GFX_Library/Adafruit_SPITFT.h:207:18: note: virtual void Adafruit_SPITFT::writePixel(int16_t, int16_t, uint16_t)
     void         writePixel(int16_t x, int16_t y, uint16_t color);
                  ^
/Users/helmar/Documents/Arduino/libraries/Adafruit_GFX_Library/Adafruit_SPITFT.h:207:18: note:   candidate expects 3 arguments, 1 provided

exit status 1
no matching function for call to 'Adafruit_ILI9341::writePixel(uint16_t)'

any idea what the problem might be ?
i assume it has something to do with incompatibilities of different versions of libraries

Here is the list of libraries and versions im using at the moment:

Bibliothek Adafruit_GFX_Library in Version 1.6.1 im Ordner: /Users/helmar/Documents/Arduino/libraries/Adafruit_GFX_Library  wird verwendet
Bibliothek Adafruit_ILI9341 in Version 1.5.1 im Ordner: /Users/helmar/Documents/Arduino/libraries/Adafruit_ILI9341  wird verwendet
Bibliothek SPI in Version 1.0 im Ordner: /Users/helmar/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/SPI  wird verwendet
Bibliothek XPT2046_Touchscreen in Version 1.3 im Ordner: /Users/helmar/Documents/Arduino/libraries/XPT2046_Touchscreen  wird verwendet
Bibliothek ESP8266WiFi in Version 1.0 im Ordner: /Users/helmar/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi  wird verwendet
Bibliothek ESP8266HTTPClient in Version 1.2 im Ordner: /Users/helmar/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266HTTPClient  wird verwendet
Bibliothek Ticker in Version 1.0 im Ordner: /Users/helmar/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/Ticker  wird verwendet
Bibliothek ArduinoOTA in Version 1.0 im Ordner: /Users/helmar/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ArduinoOTA  wird verwendet
Bibliothek ESP8266mDNS in Version 1.2 im Ordner: /Users/helmar/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266mDNS  wird verwendet
Bibliothek DNSServer in Version 1.1.1 im Ordner: /Users/helmar/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/DNSServer  wird verwendet
Bibliothek ESP8266WebServer in Version 1.0 im Ordner: /Users/helmar/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WebServer  wird verwendet
Bibliothek WiFiManager in Version 1.0.0 im Ordner: /Users/helmar/Documents/Arduino/libraries/WiFiManager  wird verwendet
Bibliothek ArduinoJson in Version 5.13.5 im Ordner: /Users/helmar/Documents/Arduino/libraries/ArduinoJson  wird verwendet
Bibliothek Json_Streaming_Parser in Version 1.0.5 im Ordner: /Users/helmar/Documents/Arduino/libraries/Json_Streaming_Parser  wird verwendet
Bibliothek ESP8266_Weather_Station in Version 1.6.6 im Ordner: /Users/helmar/Documents/Arduino/libraries/ESP8266_Weather_Station  wird verwendet
Bibliothek DHT_sensor_library in Version 1.3.0 im Ordner: /Users/helmar/Documents/Arduino/libraries/DHT_sensor_library  wird verwendet
Bibliothek simpleDSTadjust in Version 1.2.0 im Ordner: /Users/helmar/Documents/Arduino/libraries/simpleDSTadjust  wird verwendet
Bibliothek Adafruit_Sensor in Version 1.0.2 im Ordner: /Users/helmar/Documents/Arduino/libraries/Adafruit_Sensor  wird verwendet

**Comment by szybkijanek** [comment]
I've same problem

**Comment by fowlerk** [comment]
@szybkijanek, this issue was actually addressed as a separate one...see Issue 4.  Bottom line...read the README, paying particular attention to the versions of the Arduino core and libraries known to compile correctly.  I believe the error has to do with a change in the Adafruit graphics library which I have not had time to try to track down.  I probably should have closed this issue.
